---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: production
- apiVersion: v1
  kind: Namespace
  metadata:
    name: developer
- apiVersion: v1
  kind: Namespace
  metadata:
    name:qa
