---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deployment
  namespace: production
  namespace: developer
  namespace: qa
  labels:
    app: spcapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spcapp
  template:
    metadata:
      labels:
        app: spcapp 
    spec:
      containers:
      - name: spcserver
        image: nikhatsultana/spc:1.0
        ports:
        - containerPort: 8080
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: spcapp-service
spec:
  selector:
    app: spcapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
